### PR TITLE
chore: add made with section on readme

### PR DESCRIPTION
**Pull request by Ricardo-Silva91**
The section title now is very verbose.
Other possible options would be:
- Clients
- Live Websites
- Made with this boilerplate
- Used In

### CODE REVIEW

**Comment by satazor** [comment]
I like `Used in`. @andregoncalvesdev?

**Comment by andregoncalvesdev** [comment]
I like `Used in` too. Though, i like also something with `built or made`.

`Used in:`
`Built with RWM:`
`Made with RWM:`

**Comment by satazor** [comment]
I don’t have a strong opinion, you guys decide.

**Comment by Ricardo-Silva91** [comment]
I'm for 'Used in' too.

**Comment by andregoncalvesdev** [comment]
@Ricardo-Silva91 please squash the commits into `chore: add made with section on readme`, remove `platforme` and we´re good to go with this PR.

**Pull request merged**
