### PR TITLE
feat: add dockerfile

### PR DESCRIPTION
**Pull request by satazor**
The base image is from alpine LTS

### CODE REVIEW

**Review by fsdiogo — APPROVED** [review]
LGTM 👍 

Good think we can keep using the alpine version 🙂

**Comment by satazor** [comment]
@fsdiogo did `docket build . -t rwm:latest` worked for you?

**Comment by satazor** [comment]
I will will still add a socket section into the README

**Comment by fsdiogo** [comment]
@satazor Yup, it did.

When I saw you were using `alpine` instead of `carbon` I tested it just to be sure. The problem I was having in my repo must've been due to the lack of the `.dockerignore`, it was messing with the build somehow.

**Pull request merged**
